---
title: "Analysis transitions of bees between rewarding and non-rewarding flowers"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

<pre>
Analyze transition data for bee flower choice experiments
</pre>

## Set knitr options

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# define project directory
windows = ifelse(grepl(pattern = "wind", ignore.case = TRUE, 
                       x = Sys.info()[1]), TRUE, FALSE)
  
{if(grepl(pattern = "wind", ignore.case = TRUE, x = Sys.info()[1])){
  # windows
  baseDir = "D:/Dropbox/AcademiaDropbox/UW/BeeDecisionProject"
}
else{
  # mac
  baseDir = "/Users/cswitzer/Dropbox/AcademiaDropbox/UW/BeeDecisionProject"
}}

if(!dir.exists(baseDir)) stop("Directory does not exist")

knitr::opts_knit$set(root.dir = baseDir )
```


## load packages and set directories

```{r}
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if(length(new.pkg)) install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
  
packages <- c("lme4", "car","blmeco", "markovchain", "tidyverse", "msm")
ipak(packages)

# set ggplot theme
theme_set(theme_classic() + theme(text = element_text(size=12, color = "black")) )

# set directoies
dataDir = file.path(baseDir, "RawData")
dataOut = file.path(baseDir, "DataOutput")
figDir= file.path(baseDir, "Media")


# check to make sure directory exists
for(ii in c(dataDir, dataOut, figDir)){
  if(!dir.exists(ii)) stop("Directory does not exist")
}

print(dataDir)
```



## Load data

```{r}
# find newest version of dataset
newestDataset <- sort(dir(dataOut)[grepl("combinedTrials",dir(dataOut))], 
                      decreasing = TRUE)[1]


# read csv
newDF <- read_csv(file = file.path(dataOut, newestDataset))
newDF
```




```{r}
ggplot(data=newDF,aes(x=ID,fill=rewardStatus)) + 
  geom_bar(data=subset(newDF,rewardStatus=="Rewarded"),color = 'grey10', lwd = 0.1) +
  #scale_color_grey(guide = FALSE, start = 1, end = 0) + 
  geom_bar(data=subset(newDF,rewardStatus=="Unrewarded"),aes( y=..count..*(-1)), color = 'grey10', lwd = 0.1) + 
  scale_y_continuous(breaks=seq(-100,100,10),labels=abs(seq(-100,100,10))) + 
  #coord_flip() + 
  theme_classic() + 
  theme(legend.position = c(0.6,0.8) , 
        axis.text.x = element_text(angle = 90, size = 7), 
        legend.direction = "horizontal")+ 
  scale_fill_viridis_d(direction = 1, option = "cividis", name = "", end = 0.9, begin = 0.3) + 
  xlab("Bee ID") + 
  ylab("Number of visits")
#   geom_point(data = df1[!df1$packedPollen, ], aes(x = shortID, y = -80), inherit.aes = FALSE, pch = "*", size = 7) + 
#   annotate("text", x = 73, y = -70, label = "    Did not collect pollen in corbicula", size = 4) + 
# annotate("text", x = 73, y = -72, label = "*                           ", size = 8) 
# geom_point(data = newDF2, inherit.aes = FALSE, aes(x = ID_veryShort,  y = -88, color = factor(colonyNum)),
#             lwd = 4, pch = 15)+ 
#   scale_color_viridis_d(direction = 1, option = "plasma", end = 0.9, begin = 0.3, name = "Colony")
ggsave(file.path(figDir, "BeePopulationPyramid.pdf"), width = 10, height = 4)

```


## restructure data for transition analysis

```{r}
rewards1 = newDF %>%
  mutate(rewardStatus_L = (rewardStatus == "Rewarded")*1 + 1) %>%
  filter(trt_group == "LeftReward" | trt_group == "RightReward") %>%
  
  select(ID, rewardStatus_L, timestamp, packedPollen) %>%
  arrange((timestamp)) %>%
  group_by(ID) %>%
  mutate(buzzNum = row_number()) %>%
  filter(buzzNum <= 100) %>%
  ungroup() %>%
  complete(ID, buzzNum, fill = list(rewardStatus_L = 3, timestamp = "None")) %>%
  fill(packedPollen) %>%
  # keep only 1 instance of leaving
  group_by(ID, timestamp) 

rewards = rewards1 %>% 
  filter(row_number(rewardStatus_L) == 1) %>%
  mutate(packedPollen = packedPollen*1)
  
# View(rewards)

rewards

# plot proportion in each state with ggplot
rew2 <- rewards1 %>%
  ungroup() %>%
  mutate(rewardStatus_word = recode(rewardStatus_L, "1" = "No reward", 
                                   "2" = "reward", "3" = "quit"))%>%
  mutate(i = 1) %>%
  spread(rewardStatus_word, i, fill = 0 ) %>%
  group_by(buzzNum, packedPollen) %>%
  summarize(`Unrewarded` = mean(`No reward`), 
            `Rewarded` = mean(`reward`), 
            `Quit` = mean(`quit`)) %>%
  gather(key = rewardStatus, value = propReward, `Unrewarded`:`Quit`) %>%
  mutate(packedPollen2 = recode(as.character(packedPollen), 
                                "TRUE" = "Packed Pollen", 
                                "FALSE" = "No Packed Pollen"), 
         rewardStatus_2 = factor(rewardStatus, levels = c("Unrewarded", 
                                                    "Quit", 
                                                    "Rewarded"))) %>%
  mutate(rewardStatus_3 = recode_factor(rewardStatus_2, 
                                        "Unrewarded" = "Unrewarded           ", 
                                          "Quit" = "Quit           ", 
                                          "Rewarded" = "Rewarded           "))
rew2

fontsize = 10


sedPlot <- ggplot(rew2, aes(x = buzzNum, y = propReward, fill = rewardStatus_3)) + 
  geom_bar(color = NA, 
           position = 'fill', stat = "identity", alpha = 0.9, width=1) + 
  facet_wrap(.~packedPollen2, ncol = 1) + 
  scale_fill_viridis_d(direction = 1, name = "", option = "cividis") + 
   scale_color_viridis_d(direction = 1, name = "", option = "cividis", alpha = 0.4) + 
  labs(x = "Sonication Number", y = "Proportion") + 
  theme_bw() +
  theme(strip.background = element_rect(color = "black", size = 0.5, fill = "transparent"), 
        strip.text = element_text(size = fontsize, color = "black"),
        legend.title = element_blank(), 
        legend.position = c(0.6, 1.2), 
        legend.background = element_rect(color = NA, fill = NA),
        legend.direction = "horizontal",
        plot.margin = unit(c(1.1,0.5,0.1,0.1), "cm"), 
        panel.grid = element_blank(), 
        axis.line.y.right = element_blank(), 
        axis.line.x.top = element_blank(), 
        axis.ticks = element_line(size = 0.3, color = 'black'), 
        text = element_text(size=fontsize, color = "black"), 
        axis.text = element_text(size=fontsize, color = "black"), 
        axis.title = element_text(size = fontsize, color = 'black'), 
        legend.text = element_text(size = fontsize), 
        panel.border = element_rect(color = "black"), 
        plot.background = element_rect(fill = "transparent", color = NA)) + 
  scale_x_continuous(limits=c(0, 100), breaks = c(0, 50, 100), expand = c(0, 0)) + 
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.5, 1), expand = c(0,0))

sedPlot


{ggsave(file.path(figDir, "sedimentPlot.png"), 
        dpi = 500, width = 6, height = 3.5, units = 'in', bg = "transparent")
svg(file.path(figDir, "sedimentPlot.svg"), width = 6, height = 3.5)
sedPlot
dev.off()}



newDF %>% nrow
# get sample sizes
newDF %>%
  group_by(packedPollen, ID) %>%
  summarize(n = n()) %>%
  group_by(packedPollen) %>%
  summarize(n = n())

```



## multi-state model (MSM)
https://cran.r-project.org/web/packages/msm/vignettes/msm-manual.pdf

```{r}
# tabulate all transitions
statetable.msm(rewardStatus_L, ID, data = rewards)


# define the "allowed" trainsitions
Q = rbind(c(1, 1, 1), 
          c(1, 1, 1), 
          c(0, 0, 0)) # state 3 is "give up," so it is an absorbing state

# get initialization for Q matrix
Q.crude <- crudeinits.msm(rewardStatus_L ~ buzzNum , ID, data=rewards[rewards$packedPollen == 1,], qmatrix=Q)


Q.crude
# run msm  - should be run with several inital Q-vals, 
# since liklihood is maximized by numerical methods
QQ = Q * matrix(runif(n = 9), nrow = 3)
buzz_msm <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards, 
                covariates = ~packedPollen + I(buzzNum/100),
                qmatrix = QQ, exacttimes = TRUE)

buzz_msm2 <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards, 
                covariates = ~packedPollen,
                qmatrix = QQ, exacttimes = TRUE)


lrtest.msm(buzz_msm2, buzz_msm)


buzz_msm3 <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards, 
                covariates = ~packedPollen * I(buzzNum/100),
                qmatrix = QQ, exacttimes = TRUE)

lrtest.msm(buzz_msm, buzz_msm3)

buzz_msm # best model


buzz_msm

# buzz_msm <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards[rewards$packedPollen == 1,], qmatrix = Q.crude, exacttimes = TRUE)
# 
# buzz_msm <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards[rewards$packedPollen == 0,], qmatrix = Q.crude, exacttimes = TRUE)
# 
# buzz_msm

# look at two group transition matrices
qmatrix.msm(buzz_msm, covariates = list(packedPollen = 1, `I(buzzNum/100)` = 1))
qmatrix.msm(buzz_msm, covariates = list(packedPollen = 0, `I(buzzNum/100)` = 1))

```






```{r}
# plot transition probabilities over time

transProb = data.frame()

for(ii in 1:100){
  aa <- qmatrix.msm(buzz_msm, covariates = 
                      list(packedPollen = 1, `I(buzzNum/100)` = ii/100))

  # clean up diagnoals
  bb = aa$estimates + matrix(c(1,0,0,
                          0,1,0,
                          0,0,1), nrow = 3, byrow = TRUE)
  
  lower = aa$L + matrix(c(1,0,0,
                          0,1,0,
                          0,0,1), nrow = 3, byrow = TRUE)
  
  upper = aa$U + matrix(c(1,0,0,
                          0,1,0,
                          0,0,1), nrow = 3, byrow = TRUE)
  
  transProb <- rbind(transProb, c(matrix(bb, nrow = 1), 1, ii, matrix(lower, nrow = 1), matrix(upper, nrow = 1)))
}

for(ii in 1:100){
  aa <- qmatrix.msm(buzz_msm, covariates = 
                      list(packedPollen = 0, `I(buzzNum/100)` = ii/100))

  # clean up diagnoals
  bb = aa$estimates + matrix(c(1,0,0,
                          0,1,0,
                          0,0,1), nrow = 3, byrow = TRUE)
  
  lower = aa$L + matrix(c(1,0,0,
                          0,1,0,
                          0,0,1), nrow = 3, byrow = TRUE)
  
  upper = aa$U + matrix(c(1,0,0,
                          0,1,0,
                          0,0,1), nrow = 3, byrow = TRUE)
  
  transProb <- rbind(transProb, c(matrix(bb, nrow = 1), 0, ii, matrix(lower, nrow = 1), matrix(upper, nrow = 1)))
}



colnames(transProb) <-  c("t11", "t21", "t31", "t12", "t22", "t32", "t13", "t23", "t33", "packedPollen", "buzzNum", "t11L", "t21L", "t31L", "t12L", "t22L", "t32L", "t13L", "t23L", "t33L", "t11U", "t21U", "t31U", "t12U", "t22U", "t32U", "t13U", "t23U", "t33U")



transProb_long = as.tbl(transProb) %>%
  select(t11:buzzNum) %>%
  gather(key = transitionType, value = prob, -c(packedPollen, buzzNum))
transProb_long

transProb_long_err <- as.tbl(transProb) %>%
  select(packedPollen:t33U) %>%
  gather(key = transitionType_L, value = prob, -c(packedPollen, buzzNum)) %>%
  mutate(errorType = substr(.$transitionType_L, start = 4, stop = 4), 
         transitionType = substr(.$transitionType_L, start =1, stop = 3)) %>%
  select(-transitionType_L) %>%
  spread(key = errorType, value = prob, drop = TRUE) %>%
  full_join(transProb_long) %>%
  filter(!(transitionType %in% c("t31", "t32", "t33"))) %>%
  mutate(packed_pollen = recode(packedPollen, 
                                "1"="Packed Pollen", "0" = "No Packed Pollen"), 
         tranType = recode(transitionType, 
                           "t11" = "Unrewarding -> Unrewarding", 
                           "t12" = "Unrewarding -> Rewarding", 
                           "t13" = "Unrewarding -> Quit", 
                           "t21" = "Rewarding -> Unrewarding", 
                           "t22" = "Rewarding -> Rewarding", 
                           "t23" = "Rewarding -> Quit"), 
         tranType2 = recode(transitionType, 
                           "t11" = "Unrewarding -> Unrewarding", 
                           "t12" = "Unrewarding -> Rewarding", 
                           "t13" = "-> Quit", 
                           "t21" = "Rewarding -> Unrewarding", 
                           "t22" = "Rewarding -> Rewarding", 
                           "t23" = "-> Quit")) %>%
  filter(!(buzzNum > 54 & packedPollen == 0)) %>%
  mutate(transType3 = factor(tranType, 
                            levels = 
                              levels(as.factor(
                                .$tranType))[c(2,3,6,1,5, 4)]))

levels(as.factor(transProb_long_err$tranType))[c(2,3,6,1,5, 4)]

transProb_long_err


kk = ggplot(transProb_long_err, aes(x = buzzNum, y = prob, color =  packed_pollen, fill = packed_pollen)) +
  
  geom_ribbon(aes(ymin = L, ymax = U), alpha = 0.7, color = NA) + 
  geom_line(color = "black") + 
  facet_wrap(~transType3) + 
  scale_color_viridis_d(name = "") + 
  scale_fill_viridis_d(name = "", option = 'viridis',begin = 0.3, end = 0.7, 
                       direction = 1) + 
  theme(legend.position = 'top') + 
  guides(fill = guide_legend(override.aes = list(alpha = 0.7)), 
         color = guide_legend(override.aes = list(alpha = 0))) + 
  labs(x = "Sonication Number", y = "Transition Probability") + 
  scale_x_continuous(breaks = c(0, 50, 100)) + 
  scale_y_continuous(breaks = c(0, 0.5,1)) + 
  geom_hline(aes(yintercept = c(0)), lty =  3, color = 'grey40', size = 0.3) + 
  geom_hline(aes(yintercept = c(0.5)), lty =  3, color = 'grey40', size = 0.3) + 
  geom_hline(aes(yintercept = c(1)), lty =  3, color = 'grey40', size = 0.3)
kk


ggsave(file.path(figDir, "TransitionProbs.svg"), width = 8, height= 5, unit = "in")
kk + theme(panel.spacing = unit(2, "lines"), 
           panel.border = element_rect(colour = "black", fill=NA, size=0.3), 
           strip.background = element_blank(), 
           plot.background = element_rect(color = NA, fill = NA))
scalef = 2
ggsave(file.path(figDir, "TransitionProbs_spaced.svg"),  bg = "transparent",
       width = 16/scalef, height= 9/scalef, unit = "in")
ggsave(file.path(figDir, "TransitionProbs_spaced.png"), dpi = 500,  bg = "transparent",
       width = 16/scalef, height= 9/scalef, unit = "in")




oneGroup = ggplot(data = transProb_long_err[transProb_long_err$packedPollen == 1, ], aes(x = buzzNum, y = prob, color =  packed_pollen, fill = packed_pollen)) +
  
  geom_ribbon(aes(ymin = L, ymax = U), alpha = 0.5, color = NA) + 
  geom_line(color = "black") + 
  facet_wrap(~transType3) + 
  scale_color_viridis_d(name = "") + 
  scale_fill_viridis_d(name = "", option = 'viridis',begin = 0.3, end = 0.7, 
                       direction = -1) + 
  theme(legend.position = 'top') + 
  guides(fill = guide_legend(override.aes = list(alpha = 1))) + 
  labs(x = "Sonication Number", y = "Transition Probability") + 
  scale_x_continuous(breaks = c(0, 50, 100)) + 
  scale_y_continuous(breaks = c(0, 0.5,1)) + 
  geom_hline(aes(yintercept = c(0)), lty =  3, color = 'grey40', size = 0.3) + 
  geom_hline(aes(yintercept = c(0.5)), lty =  3, color = 'grey40', size = 0.3) + 
  geom_hline(aes(yintercept = c(1)), lty =  3, color = 'grey40', size = 0.3)
oneGroup


ggsave(file.path(figDir, "TransitionProbs_packed.svg"), width = 8, height= 5, unit = "in")
oneGroup + theme(panel.spacing = unit(2, "lines"), 
           panel.border = element_rect(colour = "black", fill=NA, size=0.3), 
           strip.background = element_blank())

scalef = 2
ggsave(file.path(figDir, "TransitionProbs_spaced_packed.svg"), width = 16/scalef, height= 9/scalef, unit = "in")
ggsave(file.path(figDir, "TransitionProbs_spaced_packed.png"), dpi = 500, width = 16/scalef, height= 9/scalef, unit = "in")



# get some numbers for abstract
transProb_long_err %>%
  filter(packedPollen == 1, buzzNum ==1 |buzzNum == 100, transitionType == "t12")


transProb_long_err %>%
  filter(packedPollen == 1, buzzNum ==1 |buzzNum == 100, transitionType == "t11")


transProb_long_err %>%
  filter(packedPollen == 1, buzzNum ==1 |buzzNum == 100, transitionType == "t22")


transProb_long_err %>%
  filter(packedPollen == 1, buzzNum ==1 |buzzNum == 100, transitionType == "t21")

```


# test Markovianness

```{r}
install.packages("spgs")
library(spgs)


cc = markov.test(rewards$rewardStatus_L)
print(cc)
  


?markov.test
```



```{r}

# look at transition probabilities at a certain time
pmatrix.msm(buzz_msm, t = 1, covariates = list(packedPollen = 1))
pmatrix.msm(buzz_msm, t = 1, covariates = list(packedPollen = 0))
pmatrix.msm(buzz_msm, t = 10, covariates = list(packedPollen = 0))

# sojourn times
sojourn.msm(buzz_msm, covariates = list(packedPollen = 1))


# total length of stay
totlos.msm(buzz_msm, covariates = list(packedPollen = 1))
totlos.msm(buzz_msm, covariates = list(packedPollen = 0))

# hazard ratios for transition
hazard.msm(buzz_msm)

# plot
plot(buzz_msm, covariates = list(packedPollen = 1))
plot(buzz_msm, covariates = list(packedPollen = 0))


# plot prevalence
# I don't think observed changes workds
plot.prevalence.msm(buzz_msm, mintime=0, maxtime=100, 
                    covariates = list(packedPollen = 0))


# here's a work-around
buzz_msm <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards[rewards$packedPollen == 1,], qmatrix = Q.crude, exacttimes = TRUE)
plot.prevalence.msm(buzz_msm, mintime=0, maxtime=100, ci = "normal")
#plot.survfit.msm(buzz_msm, ci = 'norm')


prevs = prevalence.msm(buzz_msm, times=seq(1,100,1))$`Expected percentages`/100

prevs2 <- as.data.frame(prevs) %>% 
  mutate(times = row_number()) %>%
  gather(key = state, value = expectedProp, -times) %>% 
  mutate(state2 = recode(as.character(.$state), 
                         "State 3" = "meanQuit", 
                         "State 1" = "meanNo", 
                         "State 2" = "meanRe"
                         ))

ggplot(prevs2, aes(x = times, y = expectedProp)) + 
  geom_line(aes(color = state2), lty = 2) + 
  geom_line(data = rew2[rew2$packedPollen == 1,], aes(x = buzzNum, y = propReward, color = interaction(rewardStatus))) + 
  theme_classic() + 
  scale_color_viridis_d(direction = -1)

# different category
buzz_msm <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards[rewards$packedPollen == 0,], qmatrix = Q.crude, exacttimes = TRUE)
plot.prevalence.msm(buzz_msm, mintime=0, maxtime=100)
#plot.survfit.msm(buzz_msm, ci = "norm")

prevs = prevalence.msm(buzz_msm, times=seq(1,100,1))$`Expected percentages`/100

prevs2 <- as.data.frame(prevs) %>% 
  mutate(times = row_number()) %>%
  gather(key = state, value = expectedProp, -times)
  


ggplot(prevs2, aes(x = times, y = expectedProp)) + 
  geom_line(aes(color = state)) + 
  geom_line(data = rew2[rew2$packedPollen == 0,], aes(x = buzzNum, y = propReward, color = interaction(rewardStatus))) + 

#  facet_wrap(.~packedPollen, labeller = "label_both", ncol = 1) + 
  theme_classic() + 
  scale_color_viridis_d(direction = -1)



```

```{r}

```

```{r}
# piecewise transition matrix
buzz_msm <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards, covariates = ~packedPollen, qmatrix = Q.crude, exacttimes = TRUE,pci = seq(2,99,10))
buzz_msm

buzz_msm2 <- msm(rewardStatus_L ~ buzzNum, subject = ID, data = rewards, covariates = ~packedPollen, qmatrix = Q.crude, exacttimes = TRUE)
buzz_msm2

pmatrix.msm(buzz_msm, t = 1, covariates = list(packedPollen = 0))

times <- c(5, 10, 50)
covariates <- list(list(packedPollen = 0), list(packedPollen = 0), list(packedPollen = 0), list(packedPollen = 4))


pmatrix.piecewise.msm(buzz_msm, t1 = 10, t2 = 20, times, covariates)
```






# markov chain

```{r}
x <- newDF2$logicalReward[newDF2$packedPollen]
xChar<-as.character(x)

mcX<-markovchainFit(xChar)$estimate
mcX
plot(mcX)


sequenceMatr <- createSequenceMatrix(x, sanitize = FALSE)
mcFitMLE <- markovchainFit(data = x)
mcFitBSP <- markovchainFit(data = x, method = "bootstrap", nboot = 5, name = "Bootstrap Mc")


# make list
myList<-list()
for (i in 1:length(unique(newDF2$ID))) {
  myList[[i]]<-as.character(newDF2$logicalReward[newDF2$ID == unique(newDF2$ID)[i]])
}

singleMcFromList<-markovchainFit(data=myList,name="listFit") #fit the MC
singleMcFromList

set.seed(123)
pdf(file.path(figDir, "BeeMarkovChain.pdf"), width = 8, height = 6)
plot(singleMcFromList$estimate)
dev.off()

```
