---
title: "Analysis for reward vs no reward pollen choice experiments"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


<pre>
Analyze data for bee flower choice experiments
</pre>




## Set knitr options

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# define project directory
windows = ifelse(grepl(pattern = "wind", ignore.case = TRUE, 
                       x = Sys.info()[1]), TRUE, FALSE)
  
{if(grepl(pattern = "wind", ignore.case = TRUE, x = Sys.info()[1])){
  # windows
  baseDir = "D:/Dropbox/AcademiaDropbox/UW/BeeDecisionProject"
}
else{
  # mac
  baseDir = "/Users/cswitzer/Dropbox/AcademiaDropbox/UW/BeeDecisionProject"
}}

if(!dir.exists(baseDir)) stop("Directory does not exist")

knitr::opts_knit$set(root.dir = baseDir )
```


## load packages and set directories

```{r}
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if(length(new.pkg)) install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
  
packages <- c("lme4", "car","blmeco", "markovchain", "tidyverse")
ipak(packages)


# set directoies
dataDir = file.path(baseDir, "RawData")
dataOut = file.path(baseDir, "DataOutput")
figDir= file.path(baseDir, "Media")


# check to make sure directory exists
for(ii in c(dataDir, dataOut, figDir)){
  if(!dir.exists(ii)) stop("Directory does not exist")
}

print(dataDir)
```



## Load data

```{r}
# find newest version of dataset
newestDataset <- sort(dir(dataOut)[grepl("combinedTrials",dir(dataOut))], 
                      decreasing = TRUE)[1]


# read csv
newDF <- read_csv(file = file.path(dataOut, newestDataset))
newDF
```

## refref: stopped here

## Summarize data

```{r}

# summary dataset
summaryDF <- newDF %>%
  mutate(accLocation = recode(.$accNum, "Dev2/ai0" = "LeftAcc", 
                              "Dev2/ai1" = "RightAcc")) %>% 
  group_by(ID, rewardStatus, accLocation, packedPollen) %>%
  count() %>%
  rename(Freq = n)

# convert to wide format
summary_wide <- summaryDF %>%
  spread(accLocation, Freq, fill = 0)
  

summary_wide2 <-  summaryDF %>% 
  spread(rewardStatus, Freq)


# insert treatment
summary_wide$trt_grp = sapply(summary_wide$ID, FUN = function(x) newDF[newDF$ID == x, "trt_group"][[1]][1])


print(summary_wide, n = Inf)

# remove rows where both rewards are 0
summary_wide = summary_wide[!((summary_wide$LeftAcc == 0) & (summary_wide$RightAcc == 0)), ]

# remove rows where both rewarded the bee
summary_wide <- summary_wide %>%
  filter(treatment != "Dev2/ai0_True__Dev2/ai1_True" & 
           treatment != "Dev2/ai0_False__Dev2/ai1_False")



summary_wide

# make sure at one column is 0
summary_wide$`Dev2/ai0` == 0 | summary_wide$`Dev2/ai1` == 0
summary_wide[!(summary_wide$`Dev2/ai0` == 0 | summary_wide$`Dev2/ai1` == 0),]

# combine to make a visit column
summary_wide$visits = summary_wide$`Dev2/ai0` + summary_wide$`Dev2/ai1`

# make wide
sw3 = spread(summary_wide[, c("ID", "rewardStatus", "visits", "treatment", "packedPollen")],   rewardStatus, visits)

# replace NA with 0
sw3$Unrewarded[is.na(sw3$Unrewarded)] = 0
sw3$Rewarded[is.na(sw3$Rewarded)] = 0

# add hive humber
sw3$colonyNum = sapply(sw3$ID, FUN = function(x) newDF[newDF$ID == x, "colonyNum"][[1]][1])
sw3$IT = sapply(sw3$ID, FUN = function(x) newDF[newDF$ID == x, "ITSpan_mm"][[1]][1])


# now we're ready for binomial regression
sw3$prop = sw3$Rewarded / (sw3$Rewarded + sw3$Unrewarded)
write_csv(sw3, path = file.path(figDir, "prelimData.csv"))

sw3$packedPollen <- plyr::mapvalues(sw3$packedPollen, from = c(TRUE, FALSE), 
                              to = c("Packed pollen", "Did not pack pollen"))

ggplot(sw3, aes(x = substr(ID, start = 7, stop = 17), y = prop-0.005, fill = packedPollen)) + 
  geom_bar(stat = "identity", colour="black", lwd = 0.1) + 
  geom_hline(aes(yintercept = 0.5), lty = 2) + 
  theme_classic()+ 
  theme(axis.text.x = element_text(angle = 40, vjust = 0.9, hjust = 1.0, size =6), 
        legend.position = "top") + 
  xlab("Timestamp") + 
  ylab("Proportion of rewarding visits") + 
  scale_fill_viridis_d(name = "", option = "D", end = 0.98)
  
ggsave(filename = file.path(figDir, "PropRewardVisits_date.svg"), width = 13/1.3, height = 5/1.3)

sw3$x2 = substr(sw3$ID, start = 7, stop = 17)
sw4 <- sw3
sw4$x2 <- factor(sw4$x2, levels = sw4$x2[order(sw4$prop, decreasing = TRUE)])
sw4$x2 <- formatC(as.numeric(as.factor(as.character(sw4$x2))), width = 2, flag = "0")
sw4$x3 <- factor(sw4$x2, levels = sw4$x2[order(sw4$prop, decreasing = TRUE)])



ggplot(sw4, aes(x = x3, y = prop-0.002, fill = packedPollen)) + 
  geom_bar(stat = "identity", colour="black", lwd = 0.1) + 
  geom_hline(aes(yintercept = 0.5), lty = 2) + 
  theme_classic()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5), 
        legend.position = c(0.8, 0.8)) + 
  xlab("Bee Number") + 
  ylab("Proportion of rewarding visits") + 
  scale_fill_viridis_d(name = "", option = "D", end = 0.98)
ggsave(filename = file.path(figDir, "PropRewardVisits_PropOrder.pdf"), width = 13/1.3, height = 5/1.3)

  
```


## GLM

```{r}

sw4 <- sw3

#  GLMER
m1 <- glmer(cbind(Rewarded, Unrewarded)~ packedPollen + (1|colonyNum) + (1|ID), family = binomial("logit"), data = sw4)
summary(m1)


# evaluate fit
dispersion_glmer(m1) #if the scale paramter is between 0.75 and 1.4, there may not be an overdispersion problem.

qqnorm(ranef(m1)$ID[,1])
qqline(ranef(m1)$ID[,1])

plot(fitted(m1), resid(m1)) #residuals vs fitted
abline(h=0)

# bad at predicting low and high
sw4$fitted <- predict(m1, type = "response") #fitted vs observed
plot(sw4$fitted, sw4$prop)
abline(0,1)


pframe <- data.frame(ID = 99999, packedPollen = c(TRUE, FALSE))
pframe$prob <- 0
pp <- predict(m1, newdata = pframe, re.form=NA, type = 'response') # re.form sets all random effects to 0

bm = bootMer(m1, FUN=function(x){
                        predict(x, 
                                pframe, 
                                re.form=NA, 
                                type = 'response')
                        }, 
             nsim = 400)

bb2_se <-apply(bm$t,2,function(x) quantile(x, probs = c(0.025, 0.975)))
pframe$blo<-bb2_se[1,]
pframe$bhi<-bb2_se[2,]
pframe$predMean <- pp
pframe <- pframe[, c("packedPollen", "blo", "bhi", "predMean")]
pframe$packedPollen <- plyr::mapvalues(pframe$packedPollen, from = c("TRUE", "FALSE"),
                                 to = c("Packed pollen", "Did not pack pollen"))
pframe


ggplot(pframe, aes(x = packedPollen, y = predMean, color = packedPollen, fill = packedPollen)) + 
  geom_errorbar(aes(ymin = blo, ymax = bhi), width = 0.11, size = 1, color = "black")  + 
  geom_errorbar(aes(ymin = blo, ymax = bhi), width = 0.1, size = 0.6)  +
  geom_point(size = 4, pch = 21, color = "black") + 
  theme_classic() + 
  theme(legend.position = "none") + 
  xlab("") + 
  ylab("Predicted proportion of visits to rewarding flower") + 
  ylim(0,1) + 
  geom_hline(aes(yintercept = 0.5), lty = 2, col = 'grey40', lwd = 0.2) + 
  scale_fill_viridis_d(end = 0.98) + 
  scale_color_viridis_d(end = 0.98)


ggsave(file.path(figDir, "propSuccessPollen_8Aug.pdf"), width = 3, height = 4)


# make thin version
ggplot(pframe, aes(x = 0, y = predMean, color = packedPollen, fill = packedPollen)) + 
  geom_errorbar(aes(ymin = blo, ymax = bhi), width = 0.12, size = 1, color = "black")  + 
  geom_errorbar(aes(ymin = blo, ymax = bhi), width = 0.1, size = 0.6)  +
  geom_point(size = 4, pch = 21, color = "black") + 
  theme_classic() + 
  theme(legend.position = "none", 
        axis.text.x = element_blank(), 
        axis.ticks.x = element_blank()) + 
  xlab("") + 
  xlim(c(-1,1))+
  ylab("Overall prop. rewarding visits") + 
  geom_hline(aes(yintercept = 0.5), lty = 2, col = 'grey40', lwd = 0.2) + 
  scale_fill_viridis_d(end = 0.98) + 
  scale_color_viridis_d(end = 0.98) + 
  scale_y_continuous(position = "right", limits = c(0,1))
ggsave(file.path(figDir, "propSuccessPollen_8Aug_thin.pdf"), width = 1, height = 3)

colSums(sw3[, 3:4])[2] / sum(colSums(sw3[, 3:4]))


# diagnostics
plot(m1)

plot(ranef(m1))

```


```{r}
# plot rolling mean
index = numeric()
for(ii in 1:nrow(newDF)){
  if(ii == 1) tmpID_old = "9999999"
  tmpID_new = newDF$ID[ii]
  if(tmpID_new != tmpID_old){
    ctr = 1
  }
  else ctr = ctr + 1
  index[ii] = ctr
  tmpID_old = tmpID_new
}

newDF$index = index



binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}

newDF2 <- newDF[newDF$index <= 100, ]


newDF2$propIndex = newDF2$index 
for(ii in 1:nrow(newDF2)){
  newDF2$propIndex[ii] = newDF2$index[ii] / sum(newDF2$ID == newDF2$ID[ii])
}


newDF2$logicalReward = as.numeric(newDF2$rewardStatus == "Rewarded")


newDF2 %>% head

newDF2$Reward_Long = plyr::mapvalues(newDF2$logicalReward, from = c(1, 0), 
                                  to = c("Reward", "No Reward"))

ggplot(newDF2, aes(x = as.factor(ID), fill = Reward_Long)) + 
  geom_bar(stat = "count") + 
  theme_classic() + 
  scale_fill_viridis_d(direction = 1, option = "D")

df1 <- as.data.frame(xtabs(~substr(newDF2$ID, 7, 17)))

names(df1)[1] <- "BeeID"
df1 <- df1[order(df1$Freq, decreasing = TRUE), ]
df1$shortID = (formatC(1:nrow(df1) + 100, width = 3, flag = "0"))

newDF2$ID_short = substr(newDF2$ID, start = 7, stop = 17)
newDF2$ID_veryShort = factor(plyr::mapvalues(newDF2$ID_short, from = as.character(df1$BeeID), to = df1$shortID), levels = df1$shortID)

df1$packedPollen = df1$BeeID %in% newDF2$ID_short[newDF2$packedPollen]



newDF2[newDF2$ID_veryShort == "111", ]
newDF2$ID_factor = factor(newDF2$ID_short, levels = levels)

ggplot(data=newDF2,aes(x=ID_veryShort,fill=Reward_Long)) + 
  geom_bar(data=subset(newDF2,Reward_Long=="Reward"),color = 'grey10', lwd = 0.1) +
  #scale_color_grey(guide = FALSE, start = 1, end = 0) + 
  geom_bar(data=subset(newDF2,Reward_Long=="No Reward"),aes( y=..count..*(-1)), color = 'grey10', lwd = 0.1) + 
  scale_y_continuous(breaks=seq(-100,100,10),labels=abs(seq(-100,100,10))) + 
  #coord_flip() + 
  theme_classic() + 
  theme(legend.position = c(0.6,0.8) , 
        axis.text.x = element_text(angle = 90, size = 7), 
        legend.direction = "horizontal")+ 
  scale_fill_viridis_d(direction = 1, option = "cividis", name = "", end = 0.9, begin = 0.3) + 
  xlab("Bee ID") + 
  ylab("Number of visits") + 
  geom_point(data = df1[!df1$packedPollen, ], aes(x = shortID, y = -80), inherit.aes = FALSE, pch = "*", size = 7) + 
  annotate("text", x = 73, y = -70, label = "    Did not collect pollen in corbicula", size = 4) + 
annotate("text", x = 73, y = -72, label = "*                           ", size = 8) 
# geom_point(data = newDF2, inherit.aes = FALSE, aes(x = ID_veryShort,  y = -88, color = factor(colonyNum)),
#             lwd = 4, pch = 15)+ 
#   scale_color_viridis_d(direction = 1, option = "plasma", end = 0.9, begin = 0.3, name = "Colony")
ggsave(file.path(figDir, "BeePopulationPyramid.pdf"), width = 10, height = 4)


ggplot(data=newDF2,aes(x=ID_short,fill= Reward_Long, group = Reward_Long)) + 
  geom_bar(data=subset(newDF2,Reward_Long=="Reward"),color = 'grey40', lwd = 0.1) +
  #scale_color_grey(guide = FALSE, start = 1, end = 0) + 
  geom_bar(data=subset(newDF2,Reward_Long=="No Reward"),aes( y=..count..*(-1)), color = 'grey40', lwd = 0.1) + 
  scale_y_continuous(breaks=seq(-100,100,10),labels=abs(seq(-100,100,10))) + 
  #coord_flip() + 
  theme_classic() + 
  theme(legend.position = "top" , 
        axis.text.x = element_text(angle = 90, size = 7))+ 
  scale_fill_viridis_d(direction = 1, option = "cividis", name = "", end = 0.9, begin = 0.3) + 
  xlab("Bee ID") + 
  ylab("Number of visits") + 
  geom_point(data = newDF2, inherit.aes = FALSE, aes(x = ID_short,  y = -88, color = factor(colonyNum)),
            lwd = 4, pch = 15)+ 
  scale_color_viridis_d(direction = 1, option = "plasma",  name = "Colony")

ggsave(file.path(figDir, "BeePopulationPyramid_date.pdf"), width = 10, height = 4)
  


 ggplot(newDF2, aes(x = propIndex, y = logicalReward)) + 
  geom_point(position = position_jitter(height = 0.1), size = 0.5) +
  binomial_smooth(aes(color = packedPollen))+  
  geom_line(alpha = 0.2) + 
  facet_wrap(~ID) + 
  theme_classic() + 
  xlab("Buzz number")+
  ylab("Reward (1: True, 0: False)")+
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank(), 
  axis.text.x = element_blank(), 
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
)

ggplot(newDF2, aes(x = index, y = logicalReward )) + 
  # geom_point(position = position_jitter(height = 0.01, width =0.05), size = 5, alpha = 0.1, pch = 21, 
  #            fill = "grey40", 
  #            colour = "grey40") +
  #geom_hex(binwidth = c(3, 0.1))+
  
  geom_bin2d(binwidth = c(2,0.3), position = position_nudge(y = 0.07))+
  #geom_line(alpha = 0.2) + 
  #facet_wrap(~ID) + 
  binomial_smooth(se = TRUE, color = 'grey40', lwd = 1)+  
  
  theme_classic() + 
  xlab("Buzz number")+
  ylab("Reward (1: True, 0: False)")+
  theme(
  strip.background = element_blank(), 
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
  ) + 
  facet_wrap(~packedPollen,labeller = label_both) + 
  ylim(c(-0.5,1.5))+ 
  geom_hline(aes(yintercept = 0.5), lty = 2) + 
  scale_fill_viridis_c(direction = -1, option = "D")

ggsave(file.path(figDir, "BeeChangeOverTime.pdf"), width = 10, height = 3)




ggplot(newDF2[, ], aes(x = index, y = logicalReward)) + 
  geom_point(position = position_jitter(height = 0.1), size = 0.5) +
  #binomial_smooth(se = FALSE)+  
  geom_line(alpha = 0.2) + 
  facet_wrap(~ID) + 
  theme_classic() + 
  xlab("Buzz number")+
  ylab("")+
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank(), 
  
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
  ) + 
  scale_y_continuous(breaks = c(0,1), labels = c("No Reward", "Reward")) + 
  scale_x_continuous(breaks = c(0, 50, 100))

ggsave(file.path(figDir, "BeeChangeOverTime_notScaled.pdf"), width = 13, height = 6)

set.seed(122)
samp = sample(unique(newDF2$ID), 6, replace = FALSE)
ggplot(newDF2[newDF2$ID %in% samp, ], aes(x = index, y = logicalReward)) + 
  geom_point(position = position_jitter(height = 0.02), size = 2, alpha = 0.7) +
  #binomial_smooth(se = FALSE)+  
  geom_line(alpha = 0.2) + 
  facet_wrap(~ID_short) + 
  theme_classic() + 
  xlab("Buzz number")+
  ylab("")+
  theme(
  strip.background = element_blank(),
  
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
  ) + 
  scale_y_continuous(breaks = c(0,1), labels = c("No Reward", "Reward")) + 
  scale_x_continuous(breaks = c(0, 50, 100))

ggsave(file.path(figDir, "BeeChangeOverTime_notScaled_small.pdf"), width = 8, height = 4)


# look at timeseries for bees that did not pack pollen
ggplot(newDF2[newDF2$packedPollen == FALSE & newDF2$ID_short %in% newDF2$ID_short[newDF2$index > 30], ], aes(x = index, y = logicalReward)) + 
  geom_point(position = position_jitter(height = 0.02), size = 2, alpha = 0.7) +
  #binomial_smooth(se = FALSE)+  
  geom_line(alpha = 0.2) + 
  facet_wrap(~ID_short) + 
  theme_classic() + 
  xlab("Buzz number")+
  ylab("")+
  theme(
  strip.background = element_blank(),
  
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
  ) + 
  scale_y_continuous(breaks = c(0,1), labels = c("No Reward", "Reward")) + 
  scale_x_continuous(breaks = seq(0, 50, 10)) 
ggsave(file.path(figDir, "BeeChangeOverTime_NoPollenPack_GreaterThan30.pdf"), width = 13, height = 8)

library(zoo)

# look at timeseries for bees that did not pack pollen
bb = newDF2[newDF2$packedPollen == FALSE, ]
bb = bb[order(bb$index), ]


ggplot(bb, aes(x = index, y = logicalReward)) + 
  geom_point(position = position_jitter(height = 0.02), size = 2, alpha = 0.7) +
  #geom_line(aes(y=rollmean(logicalReward,50, na.pad=TRUE))) +
  stat_smooth(method = "loess", span = 0.4, se = TRUE) + 
  #geom_line(alpha = 0.2) + 
  #facet_wrap(~ID_short) + 
  theme_classic() + 
  xlab("Buzz number")+
  ylab("")+
  theme(
  strip.background = element_blank(),
  
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
  ) + 
  scale_y_continuous(breaks = c(0,1), labels = c("No Reward", "Reward")) + 
  scale_x_continuous(breaks = seq(0, 50, 10)) 
ggsave(file.path(figDir, "BeeChangeOverTime_NoPollenPack_Smooth.svg"), width = 13, height = 8)



# look at timeseries for bees that did not pack pollen
bb = newDF2[newDF2$packedPollen == TRUE, ]
bb = bb[order(bb$index), ]


ggplot(bb, aes(x = index, y = logicalReward)) + 
  geom_point(position = position_jitter(height = 0.02), size = 2, alpha = 0.7) +
  #geom_line(aes(y=rollmean(logicalReward,50, na.pad=TRUE))) +
  stat_smooth(method = "loess", span = 0.4, se = FALSE) + 
  #geom_line(alpha = 0.2) + 
  #facet_wrap(~ID_short) + 
  theme_classic() + 
  xlab("Buzz number")+
  ylab("")+
  theme(
  strip.background = element_blank(),
  
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
  ) + 
  scale_y_continuous(breaks = c(0,1), labels = c("No Reward", "Reward")) + 
  scale_x_continuous(breaks = seq(0, 50, 10)) 
ggsave(file.path(figDir, "BeeChangeOverTime_PollenPack_Smooth.pdf"), width = 13, height = 8)



# look at 1st reward
ggplot(newDF2[newDF$index == 1, ], aes(x= as.factor(logicalReward))) + 
  geom_histogram(stat = "count" ) + 
  geom_errorbar()

sum(table(newDF2$logicalReward[newDF2$index == 1 ]))

prop.table(table(newDF2$logicalReward[newDF2$index == 1 ]))

pt = prop.test(table(newDF2$logicalReward[newDF2$index == 1 ]))

se = sqrt(pt$estimate * (1- pt$estimate) / sum(table(newDF2$logicalReward[newDF$index == 1 ])))
CI = data.frame(mean = c(prop.table(table(newDF2$logicalReward[newDF2$index == 1 ]))) )
CI$upper = CI$mean + 1.96 * se
CI$lower = CI$mean - 1.96 * se
CI$reward = plyr::mapvalues(row.names(CI), from = c(0,1), to = c("Unrewarding\nflower", "Rewarding\nflower"))

ggplot(CI, aes(x= reward, y = mean)) + 
  geom_point(size = 2)  + 
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.1, size = 0.6) + 
  theme_classic() + 
  geom_hline(aes(yintercept = 0.5), lty = 2, lwd = 0.3) + 
  ylab("Proportion of first visits") + 
  xlab("")
ggsave(file.path(figDir, "ProportionOfFirstVisits.pdf"), width = 4, height = 3)

```



```{r}
# visit time

newDF2 %>% head

# convert visit time to a timestamp

ttms = newDF2$timestamp %>% as.POSIXct(format="%Y_%m_%d__%H_%M_%OS")


# calculate time differences, based on timestamps
id = newDF2$ID[200]

timeDiffF = function(id){
  tmp = newDF2[newDF2$ID == id, ]
  
  tmsReformat = paste(substr(tmp$timestamp, 1, 20), substr(tmp$timestamp, 22, 999), sep = ".")
  
  ttms = tmsReformat %>% as.POSIXct(format="%Y_%m_%d__%H_%M_%OS")
  
  diffTms = as.numeric(ttms)
  
  for(jj in 1:nrow(tmp)){
    diffTms[jj] <- as.numeric(difftime(ttms[jj], ttms[1], units = "min"))
  }
  
  return(diffTms)
  
}
options(digits.mins = 3)

timeDiffs = sapply(unique(newDF2$ID), FUN = function(x) timeDiffF(x))
dd1  = as.data.frame(unlist(timeDiffs))
dd1$ID = paste0(sapply(rownames(dd1), function(x) strsplit(x, ".csv")[[1]][1]), ".csv")
dd1$index = sapply(rownames(dd1), function(x) strsplit(x, ".csv")[[1]][2]) %>% as.numeric

colnames(dd1)[1] = "TimeSinceStart"
dd1 %>% head


#merge
newDF2 %>% head

ndf3 <- merge(newDF2, dd1)

ndf3 %>% head



# plot

ggplot(ndf3[, ], aes(x = TimeSinceStart, y = logicalReward)) + 
  geom_point(position = position_jitter(height = 0.1), size = 0.5) +
  binomial_smooth( se = FALSE, aes(color = packedPollen))+  
  geom_line(alpha = 0.2) + 
  facet_wrap(~ID) + 
  theme_classic() + 
  xlab("Time since first buzz (min)")+
  ylab("Reward (1: True, 0: False)")+
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank(), 
  #axis.text.x = element_blank(), 
  panel.border = element_rect(colour = "black", fill=NA, size=0.7)
  ) + 
  scale_color_viridis_d(end = 0.97)

ggsave(file.path(figDir, "BeeChangeOverTime_min.pdf"), width = 10, height = 6)


```


```{r}
newDF2$treatment
newDF3 <- newDF2 %>%
  filter(treatment == "Dev2/ai0_False__Dev2/ai1_True" | treatment == "Dev2/ai0_True__Dev2/ai1_False")


m1 = glmer(logicalReward ~ I(index/100) * packedPollen + (1 + packedPollen | ID) + (1|colonyNum), family = binomial("logit"), data = newDF3)
summary(m1)


m12 = update(m1, .~. - I(index/100) : packedPollen)
summary(m12)
anova(m1, m12, test = "LRT")


m13 <- update(m1, .~. + I((index/100)^2))

# install.packages("gamm4")
library(gamm4)
m4 <- gamm4(logicalReward ~ s(I(index/100), by = as.factor(packedPollen)), random= ~ (1 +  packedPollen | ID) + (1|colonyNum), family = binomial("logit"), data = newDF3)
summary(m4$mer)
plot(m4$gam, pages = 1)

summary(m4$mer)

summary(m4$gam)

m3 <- glmer(logicalReward ~ I(index/100)*packedPollen + I((index/100)^2)*packedPollen + I((index/100)^3)*packedPollen  + (1 | ID) + (1|colonyNum), family = binomial("logit"), data = newDF3, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=100000)))

m33 <- update(m3, .~. - +I((index/100)^3):packedPollen)
anova(m3, m33)

m34 <- update(m3, .~. - I((index/100)^2):packedPollen)
anova(m3, m34)

summary(m34)

m35 <- update(m34, .~. - I(index/100):packedPollen)
anova(m35, m34) # m34 better

m36 <- glmer(logicalReward ~ I(index/100)*packedPollen + I((index/100)^2) +  
    I((index/100)^3) + (1 + packedPollen| ID) + (1 | colonyNum), family = binomial("logit"), data = newDF3, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=100000)) )
summary(m36)

m37 <- update(m36, .~. - I((index/100)^3) )
anova(m37, m36)

m38 <- update(m37, .~.  - I((index/100)^2))
anova(m37, m38)

summary(m38)

qqnorm(ranef(m38)$ID[,1])
qqline(ranef(m38)$ID[,1])

qqnorm(ranef(m38)$ID[,2])
qqline(ranef(m38)$ID[,2])



m39 <- update(m38, .~. - I(index/100):packedPollen)
anova(m38, m39) # BIC and AIC disagree

summary(m39)

qqnorm(ranef(m39)$ID[,1])
qqline(ranef(m39)$ID[,1])

qqnorm(ranef(m39)$ID[,2]) #wonky
qqline(ranef(m39)$ID[,2])




m3 <- glmer(logicalReward ~ I(index/100) +  (1 | ID) + (1|colonyNum), family = binomial("logit"), data = newDF3)
summary(m3)
anova(m12, m3, test = "LRT")
# different resulte b/c one ID is over-represented? 
m123 = glm(logicalReward ~ I(index/100) , family = binomial("logit"), data = newDF2[newDF2$packedPollen == FALSE,])
summary(m123)

plot(y = predict(m12, re.form = NA, type = 'response'), x = newDF3[newDF3$packedPollen == FALSE,]$index)

ggplot(newDF3, aes(x= index, y = logicalReward, color = packedPollen)) + 
  geom_point() + 
  #geom_smooth() + 
  binomial_smooth() + 
  facet_wrap(~packedPollen) + 
  scale_colour_viridis_d()

newDat = expand.grid(index = 1:100, packedPollen = c(TRUE, FALSE))
newDat <- newDat[(newDat$index <= max(newDF3$index[newDF3$packedPollen == FALSE])) |
          (newDat$packedPollen == TRUE), ]

preds = predict(m4$gam, newdata = newDat , 
                type = 'link', re.form = NA, se = TRUE)

preds = predict(m38, newdata = newDat , 
                type = 'link', re.form = NA, se = TRUE)

ilogit <- function(x){
  exp(x)/(1+exp(x))
}

str(preds)

pdframe = cbind(preds, newDat)
pdframe <- pdframe %>%
  mutate(upper = ilogit(fit + 1.96*.$se.fit), 
         lower = ilogit(fit - 1.96*.$se.fit), 
         fit = ilogit(fit))

pdframe$visitNum = pdframe$index
pdframe$packedPollen <- plyr::mapvalues(pdframe$packedPollen, from = c(TRUE, FALSE), 
                                  to = c("Packed pollen", "Did not pack pollen"))


# make density plots
bb = density(newDF3$index[newDF3$packedPollen == TRUE])
cc = density(newDF3$index[newDF3$packedPollen == FALSE])

bb$n
cc$n

dd = rbind(with(bb, 
                rbind(data.frame(x, y = y*n, packedPollen = TRUE), 
                      expand.grid(x = 100:0, y = 0, packedPollen = TRUE))), 
           with(cc, 
                rbind(data.frame(x, y = y*n, packedPollen = FALSE), 
                expand.grid(x = 100:0, y = 0, packedPollen = FALSE))))
dd <- dd[dd$x <= 100 & dd$x >= 0, ]
dd$y <- dd$y / max(dd$y)
dd$packedPollen <- plyr::mapvalues(dd$packedPollen, from = c(TRUE, FALSE), 
                                  to = c("Packed pollen", "Did not pack pollen"))

pp = ggplot(pdframe, aes(x = visitNum , y = fit, fill = packedPollen)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.5, color = NA) + 
  geom_line() + 
  theme_classic() + 
  ylim(c(0,1)) + 
  theme(legend.position = c(0.7, 0.1 ), legend.direction = "horizontal") + 
  labs(x = "Visit number", y= 'Predicted probability of\nvisiting rewarding flower') + 
  scale_fill_viridis_d(name = "", end = 0.98) + 
  scale_color_viridis_d(name = "", end = 0.98) + 
  geom_hline(aes(yintercept = 0.5), lty = 2, lwd = 0.2)  + 
  geom_hline(aes(yintercept = 1), lty = 2, lwd = 0.2) 
  #geom_point(data=newDF2, aes(x = index, y = packedPollen*0.03), pch= "|", size = 3, position = position_jitter(width = 0.5, height = 0), inherit.aes = FALSE, alpha = 1) 
pp
  
ggsave(file.path(figDir, "BeeChangeOverallPreds_index_randomslopes.pdf"), width = 7.5, height = 3)
 

pp + 
  geom_polygon(data = dd, aes(x = x, y = (y/8)-0.15, 
                              fill = relevel(factor(packedPollen), ref = "Packed pollen")), 
               color = 'grey40', lwd = 0.1, inherit.aes = FALSE, alpha = 0.5) + 

  geom_hline(aes(yintercept = 0), lwd = 0.2) + 
  theme(legend.position = c(0.7, 0.3 ), legend.direction = "horizontal") + 
  annotate("text", x = 75, y = -0.05, label = "Relative frequencies", size = 2) + 
     ylim(c(-0.15,1))
ggsave(file.path(figDir, "BeeChangeOverallPreds_index_frequencies.pdf"), width = 6.5, height = 3, device = cairo_pdf)

ggplot(newDF2, aes(x = index)) + 
  geom_polygon(data = dd, aes(x = x, y = y, fill = packedPollen), inherit.aes = FALSE, alpha = 0.1)
```

# markov chain

```{r}
x <- newDF2$logicalReward[newDF2$packedPollen]
xChar<-as.character(x)

mcX<-markovchainFit(xChar)$estimate
mcX
plot(mcX)


sequenceMatr <- createSequenceMatrix(x, sanitize = FALSE)
mcFitMLE <- markovchainFit(data = x)
mcFitBSP <- markovchainFit(data = x, method = "bootstrap", nboot = 5, name = "Bootstrap Mc")


# make list
myList<-list()
for (i in 1:length(unique(newDF2$ID))) {
  myList[[i]]<-as.character(newDF2$logicalReward[newDF2$ID == unique(newDF2$ID)[i]])
}

singleMcFromList<-markovchainFit(data=myList,name="listFit") #fit the MC
singleMcFromList

set.seed(123)
pdf(file.path(figDir, "BeeMarkovChain.pdf"), width = 8, height = 6)
plot(singleMcFromList$estimate)
dev.off()

```
